# Generated by Django 4.1.4 on 2023-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suratapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agenda', models.CharField(default='5001', max_length=100)),
                ('Sifat', models.CharField(choices=[('Biasa', 'Biasa'), ('Penting', 'Penting'), ('Segera', 'Segera'), ('Sangat Segera', 'Sangat Segera')], max_length=100)),
                ('Tujuan', models.CharField(max_length=100)),
                ('Nomor', models.CharField(default='01/KM.1/KNL.0001/2023', max_length=100)),
                ('Isi_Ringkasan', models.TextField()),
                ('Tanggal', models.DateField()),
                ('File', models.FileField(upload_to='dokumen/')),
                ('Keterangan', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='suratmasuk',
            old_name='Penerima',
            new_name='Asal',
        ),
        migrations.RenameField(
            model_name='suratmasuk',
            old_name='Pengirim',
            new_name='Tujuan',
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='Kode',
            field=models.CharField(default='0001/HM.00', max_length=100),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='Nomor',
            field=models.CharField(default='01/KM.1/KNL.0001/2023', max_length=100),
        ),
    ]
