# Generated by Django 4.1.4 on 2023-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suratapp', '0002_suratkeluar_rename_penerima_suratmasuk_asal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratmasuk',
            name='Asal_surat',
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='Keterangan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='Sifat',
            field=models.CharField(choices=[('Biasa', 'Biasa'), ('Penting', 'Penting'), ('Segera', 'Segera'), ('Sangat Segera', 'Sangat Segera')], default='Biasa', max_length=100),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='Isi_Ringkasan',
            field=models.TextField(),
        ),
    ]
