# Generated by Django 4.1.5 on 2023-03-25 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengguna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField(auto_now_add=True)),
                ('noPerkara', models.CharField(default='3125/Pdt.G', max_length=50)),
                ('jenisPerkara', models.CharField(max_length=50)),
                ('sidangKeliling', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=50)),
                ('ruangan', models.CharField(choices=[('Ruang Sidang 1', 'Ruang Sidang 1'), ('Ruang Sidang 2', 'Ruang Sidang 2'), ('Ruang Sidang 3', 'Ruang Sidang 3'), ('Ruang Sidang 4', 'Ruang Sidang 4'), ('Ruang Sidang 5', 'Ruang Sidang 5')], max_length=50)),
                ('agenda', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('pihak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.pengguna')),
            ],
        ),
    ]
