# Generated by Django 4.1.5 on 2023-03-25 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='pihak',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengguna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='pengguna',
        ),
    ]
