# Generated by Django 4.1.7 on 2023-03-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawaai_HONORER',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('tgl_lahir', models.DateField()),
                ('pendidikan', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawaai_PNS',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('NIP', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('tgl_lahir', models.DateField()),
                ('pendidikan', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
            ],
        ),
    ]
