# Generated by Django 4.1.5 on 2023-04-09 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_barang', models.CharField(max_length=50)),
                ('Nama_barang', models.CharField(max_length=50)),
                ('stok_barang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_kategori', models.CharField(max_length=50)),
                ('Nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_suplier', models.CharField(max_length=50)),
                ('Nama_suplier', models.CharField(max_length=50)),
                ('Alamat_suplier', models.TextField()),
                ('Tlpn_suplier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaksi', models.CharField(max_length=50)),
                ('tgl_transaksi', models.DateField(auto_now_add=True)),
                ('waktu_transaksi', models.TimeField(auto_now_add=True)),
                ('ambil_transaksi', models.CharField(max_length=50)),
                ('kode_barang', models.ManyToManyField(to='inventarisApp.barang')),
                ('nama_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='Kode_kategori',
            field=models.ManyToManyField(to='inventarisApp.kategori'),
        ),
        migrations.AddField(
            model_name='barang',
            name='Kode_suplier',
            field=models.ManyToManyField(to='inventarisApp.suplier'),
        ),
    ]
