# Generated by Django 4.1.5 on 2023-04-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Katagori',
        ),
    ]
