# Generated by Django 4.1.5 on 2023-04-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0005_remove_barang_id_alter_barang_kode_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id_transaksi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
