# Generated by Django 4.1.5 on 2023-04-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0006_remove_transaksi_id_alter_transaksi_id_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='Kode_suplier',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
