# Generated by Django 4.1.5 on 2023-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0007_alter_suplier_kode_suplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katagori',
            name='Kode_kategori',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
