# Generated by Django 4.1.5 on 2023-04-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarisApp', '0008_alter_katagori_kode_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='nama_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaksi', to=settings.AUTH_USER_MODEL),
        ),
    ]
