# Generated by Django 4.1.5 on 2023-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0009_alter_transaksi_nama_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='ambil_transaksi',
            field=models.CharField(db_column='Stok', max_length=50),
        ),
    ]
