# Generated by Django 4.1.5 on 2023-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisApp', '0010_alter_transaksi_ambil_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='ambil_transaksi',
            field=models.CharField(max_length=50),
        ),
    ]
