# Generated by Django 4.1.7 on 2023-03-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0007_remove_profil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenmodel',
            name='pegawai',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='absenapp.profil'),
            preserve_default=False,
        ),
    ]
