# Generated by Django 4.1.7 on 2023-03-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0008_absenmodel_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absenapp.profil'),
        ),
    ]
