# Generated by Django 4.1.7 on 2023-03-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0009_alter_absenmodel_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='pegawai',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='absenapp.profil'),
        ),
    ]
