# Generated by Django 4.1.7 on 2023-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0010_alter_absenmodel_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='bidang',
        ),
        migrations.AddField(
            model_name='profil',
            name='alamat',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='profil',
            name='jenisK',
            field=models.CharField(choices=[('Laki-Laki', 'L'), ('Perempuan', 'P')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
