# Generated by Django 4.1.5 on 2023-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0011_remove_profil_bidang_profil_alamat_profil_jenisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='status',
            field=models.CharField(choices=[('HADIR', 'HADIR'), ('IZIN', 'IZIN'), ('PULANG', 'PULANG')], default='TIDAK HADIR', max_length=50),
        ),
    ]
