# Generated by Django 4.1.5 on 2023-03-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0012_alter_absenmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absenapp.profil'),
        ),
        migrations.AlterField(
            model_name='absenmodel',
            name='status',
            field=models.CharField(choices=[('HADIR', 'HADIR'), ('IZIN', 'IZIN'), ('PULANG', 'PULANG')], default='HADIR', max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nip',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
