# Generated by Django 4.1.5 on 2023-03-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0013_alter_absenmodel_pegawai_alter_absenmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='pegawai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absenapp.profil'),
        ),
    ]
