# Generated by Django 4.1.5 on 2023-03-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenapp', '0014_alter_absenmodel_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenmodel',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='absenapp.profil'),
        ),
    ]
